<h1>Login</h1>
<div>
    <form action="" method="post">
        <div class="form-control">
            <label for="login">Login</label>
            <input type="text" id="login" name="login" placeholder="Login">
        </div>
        <div class="form-control">
            <label for="password">Password</label>
            <input type="password" id="password" name="password">
        </div>
        <button>Login</button>
    </form>
</div>